name: development
values:
  - key: baseUrl
    value: ''
    enabled: true
  - key: csrf_token
    value: ''
    enabled: true
  - key: verification_token
    value: ''
    enabled: true
  - key: user_id
    value: ''
    enabled: true
  - key: username
    value: ''
    enabled: true
  - key: session_id
    value: ''
    enabled: true
color: 180
