sonar.projectKey=Kvarell_ttrpg-platform
sonar.organization=kvarell

# Вказуємо папки, де лежить вихідний код (тільки application source)
sonar.sources=client/src,server/src

# Папки, які не треба аналізувати на баги (щоб не перевіряти чужий або тестовий код)
sonar.exclusions=**/node_modules/**,**/*.test.js,**/*.test.jsx,**/coverage/**,client/dist/**,server/prisma/**
# Вказуємо, де лежать файли з результатами тестів (твої coverage-артефакти)
# Це дозволить SonarCloud показувати відсоток покриття коду тестами!
sonar.javascript.lcov.reportPaths=client/coverage/lcov.info,server/coverage/lcov.info